### ISSUE TITLE
How to use custom fonts

### ISSUE THREAD

**Issue by RobertCordes** [typesetsh/laravel-wrapper#4]
Hi, I can't get custom fonts working. They’re in the public directory (eg. `/public/fonts/Inter-Regular.ttf`) which is an allowed directory as in the default configuration:

```php
'allowed_directories' => [
    public_path(),
],
'base_dir' => '/',
```

In my CSS I've set the following:
```css
@font-face {
    font-family: "Inter";
    src: url("/public/fonts/Inter-Regular.ttf") format("ttf");
    /* I also tried src: url("/fonts/Inter-Regular.ttf") format("ttf"); */
    font-weight: 400;
}
```
But I had no luck. I also tried using .woff. Do you have any idea what the problem could be?

PS: I love your package! ❤️

**Comment by jsiefer** [comment]
Hi (otf, ttf, woff (not woff2)) should work. 

Most likely there is an issue with the path mapping. Sadly the Laravel plugin does "swallow" those warnings at the moment. If you can xdebug into it, checkout `\Typesetsh\LaravelWrapper\Typesetsh::render()` and check the `$this->uriResolver->errors` after `html2pdf->render` is called.

Since its its properly relative to your project root, you can try to do:

```css
@font-face {
    font-family: "Inter";
    src: url("./fonts/Inter-Regular.ttf") format("ttf");
    /* I also tried src: url("/fonts/Inter-Regular.ttf") format("ttf"); */
    font-weight: 400;
}

```

```php
'allowed_directories' => [
    public_path(),
],
'base_dir' => public_path(),

```

Doing above should tell the UriResolver to prepend the public path to all ./ resources.



----

- [ ] Improve error reporting using the UriResolver
- [ ] default base path should probably be empty string
